language: node_js

jobs:
  include:
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      before_install:
        - yarn global add @chialab/rna-cli
      install:
        - yarn install
        - yarn add codecov
      script:
        - yarn test
      after_success:
        - cat test/__coverage__/*/lcov.info | ./node_modules/.bin/codecov

  allow_failures:
    - env: CI_BUILD_TYPE=saucelabs

addons:
  apt:
    packages:
      - xvfb
