language: node_js

jobs:
  include:
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      before_install:
        - yarn global add @chialab/rna-cli
      install:
        - rna install
        - rna add codecov
      script:
        - rna unit 'test/*.tests.js' --saucelabs --coverage --concurrency 1
      after_success:
        - cat reports/unit/coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov

  allow_failures:
    - env: CI_BUILD_TYPE=saucelabs

addons:
  apt:
    packages:
      - xvfb
